import type { Metadata } from "next";
import { LegalPage, SUPPORT_EMAIL } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service">
      <p>
        These terms govern your use of Hastrekha AI (&quot;the app&quot;, &quot;we&quot;, &quot;us&quot;). By signing in you
        agree to them.
      </p>

      <h2>1. Entertainment only</h2>
      <p>
        Hastrekha AI provides AI-generated palm readings inspired by Indian palmistry (Samudrika Shastra). Readings and
        chat answers are for <strong>entertainment and self-reflection only</strong>. They are not scientific
        predictions and are not medical, psychological, legal, financial or investment advice. Do not make important
        decisions based on them; consult a qualified professional instead.
      </p>

      <h2>2. Eligibility</h2>
      <p>You must be at least 18 years old. Readings are not generated for dates of birth under 18.</p>

      <h2>3. Your account</h2>
      <ul>
        <li>You sign in with Google or an Indian mobile number verified by OTP.</li>
        <li>Each person may receive one free reading. Creating multiple accounts to obtain extra free readings is not allowed.</li>
        <li>Only upload photos of your own palm, or of someone who has given you permission.</li>
        <li>You can delete individual readings or your whole account at any time from within the app.</li>
      </ul>

      <h2>4. Pricing and credits</h2>
      <ul>
        <li>New accounts get 1 free reading with 1 chat question.</li>
        <li>After that, each reading costs ₹99 (inclusive of applicable taxes) and includes 10 chat questions.</li>
        <li>A reading credit is used only when a reading is successfully generated. If the photo is rejected or the AI fails, the credit is not used.</li>
        <li>Chat questions belong to the reading they were bought with and do not expire.</li>
        <li>Payments are processed by Razorpay. See our <a className="text-maroon underline" href="/refund">Refund Policy</a>.</li>
      </ul>

      <h2>5. Acceptable use</h2>
      <p>
        Do not misuse the service, attempt to access other users&apos; data, overload it with automated requests, or use
        it for unlawful purposes. We apply reasonable rate limits and may suspend accounts that abuse the service.
      </p>

      <h2>6. AI output</h2>
      <p>
        Readings are generated by third-party AI models and may be inaccurate or inconsistent. We instruct the AI to be
        respectful and to avoid fear-based predictions, but we cannot guarantee every response.
      </p>

      <h2>7. Liability</h2>
      <p>
        To the extent permitted by law, the service is provided &quot;as is&quot; and our total liability for any claim is
        limited to the amount you paid us in the 3 months before the claim.
      </p>

      <h2>8. Changes and contact</h2>
      <p>
        We may update these terms; material changes will be shown in the app. Questions:{" "}
        <a className="text-maroon underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. These terms are
        governed by the laws of India.
      </p>
    </LegalPage>
  );
}
